input_file='exemplo/arquivo.txt'
matrix_file='exemplo/matrix.txt'
matrix_u_file='exemplo/matrix_u.txt'
matrix_s_file='exemplo/matrix_s.txt'
matrix_v_file='exemplo/matrix_v.txt'
find_terms='human user'
frequency=''
score='dot'
debug=0